language: python

python:
  - "3.5"

before_install:
  - pip install codecov    

install:
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt

script:
  - nosetests -v --with-coverage --cover-package=mcheck --cover-inclusive

after_success:
  - codecov
